version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment: 
      POSTGRES_DB: "test-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    